
version: '3'

services:
  mysql:
    image: mysql
    container_name: kata_manga_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: KataManga
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kata_manga_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - 8080:80
  backend:
    build: ./kata-manga-backend/kata-manga-backend
    container_name: kata_manga_backend
    links:
      - mysql
    restart: always
    ports:
      - 5225:5225